### ISSUE TITLE
vot-cli: TypeError: crypto.getRandomValues is not a function

### ISSUE THREAD

**Issue by spacedream** [ilyhalight/voice-over-translation#104]
полный лог из консоли:

$> vot-cli "https://www.youtube.com/watch?v=X98VPQCE_WI" "https://www.youtube.com/watch?v=djr8j-4fS3A&t=900s" --output="."
file:///home/user/tmp/voice-over-translation-1.0.9.9/vot-cli/getTranslate.js:46
    var uuid = ([1e7]+1e3+4e3+8e3+1e11).replace(/[018]/g, c => (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16));
                                                                           ^

TypeError: crypto.getRandomValues is not a function
    at file:///home/user/tmp/voice-over-translation-1.0.9.9/vot-cli/getTranslate.js:46:76
    at String.replace (<anonymous>)
    at getUUID (file:///home/user/tmp/voice-over-translation-1.0.9.9/vot-cli/getTranslate.js:46:41)
    at requestVideoTranslation (file:///home/user/tmp/voice-over-translation-1.0.9.9/vot-cli/getTranslate.js:51:18)
    at translateVideo (file:///home/user/tmp/voice-over-translation-1.0.9.9/vot-cli/getTranslate.js:87:3)
    at translateAndDownload (file:///home/user/tmp/voice-over-translation-1.0.9.9/vot-cli/index.js:31:3)
    at file:///home/user/tmp/voice-over-translation-1.0.9.9/vot-cli/index.js:96:3
    at Array.forEach (<anonymous>)
    at file:///home/user/tmp/voice-over-translation-1.0.9.9/vot-cli/index.js:93:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
$>

**Comment by ilyhalight** [comment]
Какая версия NodeJS установлена?

**Comment by spacedream** [comment]
nodejs/unknown,now 16.19.1-deb-1nodesource1 amd64 [installed]
  Node.js event-based server-side javascript engine

**Comment by ilyhalight** [comment]
До 17 или выше обновитесь и должно заработать
