### ISSUE TITLE
VOT-Cli TypeError: crypto.getRandomValues is not a function

### ISSUE THREAD

**Issue by Spp595** [ilyhalight/voice-over-translation#89]
Не работает vot-cli, os: Arch Linux
```
TypeError: crypto.getRandomValues is not a function
    at file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:46:76
    at String.replace (<anonymous>)
    at getUUID (file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:46:41)
    at requestVideoTranslation (file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:51:18)
    at translateVideo (file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:87:3)
    at translateAndDownload (file:///home/sp595/yndx-translate/vot-cli/index.js:31:3)
    at file:///home/sp595/yndx-translate/vot-cli/index.js:96:3
    at Array.forEach (<anonymous>)
    at file:///home/sp595/yndx-translate/vot-cli/index.js:93:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
```

**Comment by ilyhalight** [comment]
Какая версия NodeJS?

**Comment by Spp595** [comment]
Появилась новая ошибка
```
file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:46
    var uuid = ([1e7]+1e3+4e3+8e3+1e11).replace(/[018]/g, c => (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16));
                                                                           ^

TypeError: crypto.getRandomValues is not a function
    at file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:46:76
    at String.replace (<anonymous>)
    at getUUID (file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:46:41)
    at requestVideoTranslation (file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:51:18)
    at translateVideo (file:///home/sp595/yndx-translate/vot-cli/getTranslate.js:87:3)
    at translateAndDownload (file:///home/sp595/yndx-translate/vot-cli/index.js:31:3)
    at file:///home/sp595/yndx-translate/vot-cli/index.js:96:3
    at Array.forEach (<anonymous>)
    at file:///home/sp595/yndx-translate/vot-cli/index.js:93:10
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)

```

**Comment by ilyhalight** [comment]
> 8.19.2

Минимальная поддерживаемая версия NodeJS 17+
